AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - "spec/**/*"
  

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 200

Style/Documentation: 
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 18

Metrics/BlockLength:
  Max: 50

Metrics/AbcSize:
  Max: 23

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/MissingRespondToMissing:
  Enabled: false